parameters:
    # Adds a fallback DATABASE_URL if the env var is not set. This allows you
    # to run cache:warmup even if your environment variables are not available
    # yet. You should not need to change this value.
    # env(DATABASE_URL): 'mysql://root:@127.0.0.1:3306/shagforflags'

doctrine:
    dbal:
        driver: 'pdo_mysql'
        host: "127.0.0.1"
        port: "3306"
        dbname: "shagforflags"
        user: "root"
        password: ""
        charset: UTF8MB4
        #url: 'mysql://root:@127.0.0.1:3306/shagforflags'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
